### ISSUE TITLE
getCurrentStyle and getNetworkName don't work with base.url specified

### ISSUE THREAD

**Issue by risserlin** [cytoscape/RCy3#208]
Not sure if this related to the this issue[#191 ] but getCurrentStyle and getNetworkName don't work with the base.url specified

Using the latest version of bioconductor (3.17.1) and RCy3 (2.20)

<img width="821" alt="Screen Shot 2023-07-25 at 10 48 24 AM" src="https://github.com/cytoscape/RCy3/assets/3842763/a558a512-c255-43af-94e0-b6dcd555b535">

**Comment by AlexanderPico** [comment]
Fixed and pushed to GitHub. Can install from there or wait for dev release from Bioc. Thanks for reporting!

**Comment by risserlin** [comment]
Thanks for the really fast turn around on this. 

I uninstalled the current version of RCy3.  And I now have 1.21.1 version installed (through devtools::install_github) but the error is still there unfortunately. 

Any idea what I did wrong. 
<img width="881" alt="Screen Shot 2023-07-25 at 3 38 12 PM" src="https://github.com/cytoscape/RCy3/assets/3842763/e9d85004-b499-4f39-a21f-19da903b73a4">

**Comment by AlexanderPico** [comment]
Looks like the installation was skipped since it was detected to be identical to what you already had installed :)

Try `devtools::install_github("https://github.com/cytoscape/RCy3/tree/devel")`

**Comment by risserlin** [comment]
I uninstalled and re-installed using the above and it is still the same thing.  (I had the skipped installation message to show that I had installed the latest github update - [5a26218](https://github.com/cytoscape/RCy3/commit/5a26218811283ea51cfd81867fffab8cd636159c) which was the commit from yesterday.

Still getting the same error.  - 'object '"networks"' not found'

**Comment by risserlin** [comment]
I tried installing the way you suggested but still the same issue.  (I included the skipping install statement to show that I had the latest version installed.  the 5a262188 is the latest version on github) and even with that one installed I am getting the same error.  

I tried adding the network name or network Suid to the call to see if it is was just an obscure error message but that didn't help.  
<img width="744" alt="Screen Shot 2023-07-26 at 11 53 21 AM" src="https://github.com/cytoscape/RCy3/assets/3842763/0239c7fb-4e7c-4d6e-8cf5-255dededb8bf">

What is this line supposed to do?
Error in cyrestGET("networks", base.url = base.url) : 
  object '"networks"' not found

**Comment by AlexanderPico** [comment]
Weird. Maybe try loading the new function code directly in your R session, like copy/paste the function code and run it.  - AlexOn Jul 26, 2023, at 8:54 AM, Ruth Isserlin ***@***.***> wrote:﻿
I tried installing the way you suggested but still the same issue.  (I included the skipping install statement to show that I had the latest version installed.  the 5a26218 is the latest version on github) and even with that one installed I am getting the same error.
I tried adding the network name or network Suid to the call to see if it is was just an obscure error message but that didn't help.

What is this line supposed to do?
Error in cyrestGET("networks", base.url = base.url) :
object '"networks"' not found

**Comment by risserlin** [comment]
I have no idea what the issue (I cut and copied the updated methods in but it still didn't help) is but I can get it to work by running this command instead (which is basically exactly what is in the getCurrentStyle function) ... so weird. 

Works - 
`res <- cyrestGET(paste("networks", getNetworkSuid("current",base.url=current_base),
                       "views",getNetworkViewSuid(network="current",base.url = current_base),
                       "currentStyle", sep="/"), 
                 base.url = current_base)`

Doesn't work - 
`RCy3::getCurrentStyle(network = "current",base.url = current_base)`

The error message changed a bit since cutting and copying the updated methods in though

<img width="758" alt="Screen Shot 2023-07-26 at 1 09 31 PM" src="https://github.com/cytoscape/RCy3/assets/3842763/e8345a87-9645-4053-9fb3-82246f1b98ac">

**Comment by AlexanderPico** [comment]
I'll increment the version and push to bioc-devel soon. Maybe that will "reset" things on your end and you won't need the workaround anymore.

The updated functions work for me, so it's hard for me to diagnose the remaining issues you are seeing. Thanks again for reporting the bug!
