### ISSUE TITLE
Edge attributes in multigraphs

### ISSUE THREAD

**Issue by jonaszierer** [cytoscape/RCy3#41]
When creating a multigraph (i.e. a graph with multiple edges between the same pair of vertices) edge attributes are not transferred correctly to Cytoscape. Specifically, all edges between one pair of nodes will have the same edge attributes. for instance:

```
require(igraph)
require(RCy3)
graph <- graph_from_data_frame(data.frame(v1 = rep("A", 2),
                                          v1 = rep("B", 2),
                                          type = c("E1", "E2")))
createNetworkFromIgraph(graph, "graph")
```

Both edges will have `type = E2` in cytoscape. When you i.e. try to colour edges by type all of them will have the same colour.

**Comment by AlexanderPico** [comment]
Fixed in 2.2.6. Will be updated at bioconductor within 48 hours. Available now via github:

```
install.packages("devtools")
library(devtools)
install_github('cytoscape/RCy3', build_vignettes=TRUE)
library(RCy3)
```

**Comment by jonaszierer** [comment]
Thanks for the quick fix! There still seems to be a problem in large networks. If there are too many multi-edges (haven't quite found out how many) some edge attributes are lost. Try this:

```
require(igraph)
require(RCy3)
set.seed(1)
nn <- 100
t  <- 4
graph         <- erdos.renyi.game(n = nn, p = 0.1)
E(graph)$type <- sample(letters, length(E(graph)), replace = T)
graph         <- add_edges(graph, sample(1:nn, size = nn*t*2, replace = T), attr = list(type = sample(letters, nn*t, replace = T)))
createNetworkFromIgraph(graph, "graph")
```

**Comment by SuhasSrinivasan** [comment]
This issue still exists in RCy3 - 2.2.6 and it is quite severe.
For a network with 200 vertices and 2446 edges, the edge attributes on 1/3rd of edges are completely missing.
Please find attached a screenshot with edges that are missing the `e_color` attribute and the data file to replicate the issue.
R - 3.5.2
igraph - 1.2.4
Cytoscape - 3.7.1
Java - 1.8

```
library(igraph)
library(RCy3)

frame1 = read.table("module_df.tsv", sep = "\t", header = T)
head(frame1)
module = graph_from_data_frame(frame1[, 1:2], directed = F)
module = set.edge.attribute(module, "e_color", index = E(module), value = frame1$e_color)
summary(module)

cytoscapePing()
createNetworkFromIgraph(module)
layoutNetwork("degree-circle")
```   
Screenshot:   
![Cytoscape Table View](https://user-images.githubusercontent.com/32346517/56463717-6a8fad80-63a7-11e9-948f-ea02a7bdeb99.png)
   
Data:   
[module_df.txt](https://github.com/cytoscape/RCy3/files/3100729/module_df.txt)

**Comment by AlexanderPico** [comment]
Thank you both for the additional tests. I can reproduce this.

**Comment by AlexanderPico** [comment]
Fixed in upcoming 2.4.0.  Available now via github:

```
install.packages("devtools")
library(devtools)
install_github('cytoscape/RCy3', build_vignettes=TRUE)
library(RCy3)
```

**Comment by AlexanderPico** [comment]
Updated solution tested with examples above. See https://github.com/cytoscape/RCy3/issues/115
